<a href="https://colab.research.google.com/github/Kuldeep2003-exe/sklearn/blob/main/Classification_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [2]:
y

array([0, 1, 1, 1])

In [3]:
w = np.array([1,1])
w

array([1, 1])

In [4]:
b = -0.5

In [9]:
pred = []
for a in x:
  y_hat = np.dot(a,w)+b
  pred.append(activation(y_hat))

In [10]:
pred

[0, 1, 1, 1]

In [8]:
def activation(z):
  if z >= 0:
    return 1
  else:
    return 0